---
platform: linux

image_resource:
  type: docker-image
  source: {repository: concourse/static-golang}

inputs:
- name: github-release-resource
  path: gopath/src/github.com/concourse/github-release-resource

outputs:
- name: built-resource

run:
  path: gopath/src/github.com/concourse/github-release-resource/scripts/ci
